name = "advent-of-code"
srcDir = "src"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "Parser"
git = "https://github.com/fgdorais/lean4-parser"
rev = "main"

[[lean_exe]]
name = "Day1"
srcDir = "Day1"

[[lean_lib]]
name = "Day2"

[[lean_exe]]
name = "Day2"
srcDir = "Day2"

[[lean_lib]]
name = "Day3"

[[lean_exe]]
name = "Day3"
srcDir = "Day3"